/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/3d-models/oficina_setup.glb -o ./src/components/ModeloOficina.tsx -t 
*/

import * as THREE from "three";
import React, { useState } from "react";
import { useGLTF, Text } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import modeloUrl from '@/assets/3d-models/oficina_setup.glb';

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_11: THREE.Mesh;
    Cube: THREE.Mesh;
    Plane: THREE.Mesh;
    Pantalla: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube006: THREE.Mesh;
    Circle: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    ["G-PLANTS_1_0001"]: THREE.Mesh;
    ["G-PLANTS_1_0001_1"]: THREE.Mesh;
    ["G-PLANTS_1_0001_2"]: THREE.Mesh;
    ["G-Plants_Set_47001"]: THREE.Mesh;
    ["G-Plants_Set_47001_1"]: THREE.Mesh;
    ["G-Plants_Set_47001_2"]: THREE.Mesh;
    ["G-Plants_Set_47001_3"]: THREE.Mesh;
    ["G-Plants_Set_47001_4"]: THREE.Mesh;
    ["G-Plants_Set_47001_5"]: THREE.Mesh;
    ["G-Plants_Set_47001_6"]: THREE.Mesh;
    ["G-Plants_Set_47001_7"]: THREE.Mesh;
    Back_Board_Cube009_1: THREE.Mesh;
    Back_Board_Cube009_2: THREE.Mesh;
    Horizontal_Board_1_Cube012: THREE.Mesh;
    Horizontal_Board_2_Cube008: THREE.Mesh;
    Horizontal_Board_3_Cube000: THREE.Mesh;
    Horizontal_Board_4_Cube015: THREE.Mesh;
    Vertical_Board_1_Cube007: THREE.Mesh;
    Vertical_Board_2_Cube013: THREE.Mesh;
    Vertical_Board_3_Cube006: THREE.Mesh;
    Vertical_Board_4_Cube014: THREE.Mesh;
    prop_books_01_inst_001: THREE.Mesh;
    Sphere: THREE.Mesh;
  };
  materials: {
    ["back_panel-black"]: THREE.MeshStandardMaterial;
    Black_Plastic: THREE.MeshStandardMaterial;
    glass: THREE.MeshStandardMaterial;
    photos: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["Material.011"]: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["Clay 01"]: THREE.MeshStandardMaterial;
    PLANTS_1_wire_115115115: THREE.MeshStandardMaterial;
    red_dirt_mud_01: THREE.MeshStandardMaterial;
    ["Marble White"]: THREE.MeshStandardMaterial;
    Metal01: THREE.MeshStandardMaterial;
    Plants_Set_stem1: THREE.MeshStandardMaterial;
    Plants_Set_branch1: THREE.MeshStandardMaterial;
    ["Plants_Set_leaf 7"]: THREE.MeshStandardMaterial;
    ["Plants_Set_leaf 8"]: THREE.MeshStandardMaterial;
    ["Plants_Set_leaf 9"]: THREE.MeshStandardMaterial;
    Wood_Veneer: THREE.MeshStandardMaterial;
    White_Veneer: THREE.MeshStandardMaterial;
    prop_books_01_mt: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"] & {
  onPantallaClick?: () => void;
}) {
  const { onPantallaClick, ...restProps } = props;
  const { nodes, materials } = useGLTF(modeloUrl) as GLTFResult;

  const handlePantallaClick = (e: any) => {
    e.stopPropagation();
    
    if (onPantallaClick) {
      onPantallaClick();
    }
  };

  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.586, 1.363, -0.998]}
        rotation={[0.043, 0, 0]}
        scale={1.129}
      >
        <group
          position={[0.046, 0.04, 0.015]}
          rotation={[-0.042, -0.006, -0.024]}
          scale={0.963}
        >
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials["back_panel-black"]}
            />
            <mesh
              geometry={nodes.Object_7.geometry}
              material={materials.Black_Plastic}
            />
            <mesh
              geometry={nodes.Object_9.geometry}
              material={materials.glass}
              position={[0, 0.01, 0]}
            />
            <mesh
              geometry={nodes.Object_11.geometry}
              material={materials.photos}
              position={[0, 0.004, 0]}
            />
          </group>
        </group>
      </group>

      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.006"]}
        position={[-0.083, 0, -0.628]}
      />

      <mesh
        geometry={nodes.Pantalla.geometry}
        material={materials["Material.005"]}
        position={[-0.083, 0, -0.628]}
        onClick={handlePantallaClick} 
        onPointerOver={(e) => {
          e.stopPropagation();
          document.body.style.cursor = "pointer";
        }}
        onPointerOut={() => {
          document.body.style.cursor = "default";
        }}
      >
        
      </mesh>

      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.004"]}
        position={[-0.054, 0, -0.628]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials["Material.008"]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials["Material.011"]}
      />
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials["Material.009"]}
        position={[0, 0.043, 0]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.010"]}
      />

      <group
        position={[0.491, 1.383, -0.846]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.449}
      >
        <mesh
          geometry={nodes["G-PLANTS_1_0001"].geometry}
          material={materials["Clay 01"]}
        />
        <mesh
          geometry={nodes["G-PLANTS_1_0001_1"].geometry}
          material={materials.PLANTS_1_wire_115115115}
        />
        <mesh
          geometry={nodes["G-PLANTS_1_0001_2"].geometry}
          material={materials.red_dirt_mud_01}
        />
      </group>

      <group position={[-0.744, 0.152, 0.811]} scale={0.724}>
        <mesh
          geometry={nodes["G-Plants_Set_47001"].geometry}
          material={materials.red_dirt_mud_01}
        />
        <mesh
          geometry={nodes["G-Plants_Set_47001_1"].geometry}
          material={materials["Marble White"]}
        />
        <mesh
          geometry={nodes["G-Plants_Set_47001_2"].geometry}
          material={materials.Metal01}
        />
        <mesh
          geometry={nodes["G-Plants_Set_47001_3"].geometry}
          material={materials.Plants_Set_stem1}
        />
        <mesh
          geometry={nodes["G-Plants_Set_47001_4"].geometry}
          material={materials.Plants_Set_branch1}
        />
        <mesh
          geometry={nodes["G-Plants_Set_47001_5"].geometry}
          material={materials["Plants_Set_leaf 7"]}
        />
        <mesh
          geometry={nodes["G-Plants_Set_47001_6"].geometry}
          material={materials["Plants_Set_leaf 8"]}
        />
        <mesh
          geometry={nodes["G-Plants_Set_47001_7"].geometry}
          material={materials["Plants_Set_leaf 9"]}
        />
      </group>

      <group position={[0.261, 1.308, -0.898]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Back_Board_Cube009_1.geometry}
          material={materials.Wood_Veneer}
        />
        <mesh
          geometry={nodes.Back_Board_Cube009_2.geometry}
          material={materials.White_Veneer}
        />
      </group>

      <mesh
        geometry={nodes.Horizontal_Board_1_Cube012.geometry}
        material={materials.White_Veneer}
        position={[0.261, 1.308, -0.898]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Horizontal_Board_2_Cube008.geometry}
        material={materials.White_Veneer}
        position={[0.261, 1.308, -0.898]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Horizontal_Board_3_Cube000.geometry}
        material={materials.White_Veneer}
        position={[0.261, 1.308, -0.898]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Horizontal_Board_4_Cube015.geometry}
        material={materials.White_Veneer}
        position={[0.261, 1.308, -0.898]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Vertical_Board_1_Cube007.geometry}
        material={materials.White_Veneer}
        position={[0.261, 1.308, -0.898]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Vertical_Board_2_Cube013.geometry}
        material={materials.White_Veneer}
        position={[0.261, 1.308, -0.898]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Vertical_Board_3_Cube006.geometry}
        material={materials.White_Veneer}
        position={[0.261, 1.308, -0.898]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Vertical_Board_4_Cube014.geometry}
        material={materials.White_Veneer}
        position={[0.261, 1.308, -0.898]}
        rotation={[Math.PI / 2, 0, 0]}
      />

      <mesh
        geometry={nodes.prop_books_01_inst_001.geometry}
        material={materials.prop_books_01_mt}
        position={[0.636, 1.026, -0.895]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0.005}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials["Material.007"]}
        position={[0.235, 0.049, -0.13]}
        scale={[-0.483, -0.015, -0.558]}
      />
    </group>
  );
}

useGLTF.preload(modeloUrl);
